In [4]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import files

uploaded = files.upload()

Saving loan_data_2007_2014.csv to loan_data_2007_2014.csv

In [5]:
df = pd.read_csv("loan_data_2007_2014.csv")

/tmp/ipykernel_1678/4277137087.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("loan_data_2007_2014.csv")

In [7]:
df.shape

(466285, 75)

In [6]:
df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df["loan_status"].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [9]:
resolved_df = df[
    df["loan_status"].isin(["Fully Paid", "Charged Off", "Default"])
].copy()

In [10]:
resolved_df.shape

(228046, 75)

In [11]:
resolved_df["target"] = np.where(
    resolved_df["loan_status"].isin(["Charged Off", "Default"]),
    1,
    0
)

In [12]:
resolved_df["target"].value_counts()

target
0    184739
1     43307
Name: count, dtype: int64

In [13]:
resolved_df["target"].value_counts(normalize=True)

target
0    0.810095
1    0.189905
Name: proportion, dtype: float64

In [14]:
resolved_df.isnull().sum()

Unnamed: 0               0
id                       0
member_id                0
loan_amnt                0
funded_amnt              0
                     ...
total_rev_hi_lim     63726
inq_fi              228046
total_cu_tl         228046
inq_last_12m        228046
target                   0
Length: 76, dtype: int64

In [15]:
resolved_df.isnull().sum().sort_values(ascending=False).head(20)

inq_fi                         228046
all_util                       228046
max_bal_bc                     228046
open_rv_24m                    228046
open_rv_12m                    228046
il_util                        228046
total_bal_il                   228046
mths_since_rcnt_il             228046
open_il_24m                    228046
open_il_12m                    228046
open_il_6m                     228046
open_acc_6m                    228046
annual_inc_joint               228046
dti_joint                      228046
verification_status_joint      228046
total_cu_tl                    228046
inq_last_12m                   228046
next_pymnt_d                   227214
mths_since_last_record         201260
mths_since_last_major_derog    187814
dtype: int64

In [16]:
resolved_df.columns[resolved_df.isnull().sum() == 0]

Index(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'purpose', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'policy_code', 'application_type', 'acc_now_delinq',
       'target'],
      dtype='object')

In [17]:
resolved_df.dtypes

Unnamed: 0            int64
id                    int64
member_id             int64
loan_amnt             int64
funded_amnt           int64
                     ...
total_rev_hi_lim    float64
inq_fi              float64
total_cu_tl         float64
inq_last_12m        float64
target                int64
Length: 76, dtype: object

In [18]:
resolved_df.select_dtypes(include="number").columns
resolved_df.select_dtypes(include="object").columns

Index(['term', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       'home_ownership', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'earliest_cr_line', 'initial_list_status', 'last_pymnt_d',
       'next_pymnt_d', 'last_credit_pull_d', 'application_type'],
      dtype='object')

In [19]:
resolved_df.select_dtypes(include="number").columns

Index(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'annual_inc_joint',
       'dti_joint', 'verification_status_joint', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_il_6m',
       'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il',
       'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'target'],
      dtype='object')

In [20]:
resolved_df[[
    "loan_amnt", "funded_amnt", "funded_amnt_inv",
    "int_rate", "installment", "annual_inc", "dti",
    "delinq_2yrs", "inq_last_6mths", "open_acc",
    "pub_rec", "revol_bal", "revol_util", "total_acc"
]].isnull().sum()

loan_amnt            0
funded_amnt          0
funded_amnt_inv      0
int_rate             0
installment          0
annual_inc           0
dti                  0
delinq_2yrs          0
inq_last_6mths       0
open_acc             0
pub_rec              0
revol_bal            0
revol_util         186
total_acc            0
dtype: int64

In [21]:
resolved_df[[
    "term", "grade", "sub_grade", "emp_length",
    "home_ownership", "verification_status",
    "purpose", "initial_list_status", "application_type"
]].isnull().sum()

term                      0
grade                     0
sub_grade                 0
emp_length             8721
home_ownership            0
verification_status       0
purpose                   0
initial_list_status       0
application_type          0
dtype: int64

In [22]:
resolved_df["issue_d"].value_counts().sort_index()

issue_d
Apr-08     155
Apr-09     290
Apr-10     827
Apr-11    1415
Apr-12    3046
          ...
Sep-10    1086
Sep-11    1883
Sep-12    5690
Sep-13    6369
Sep-14    2729
Name: count, Length: 91, dtype: int64

In [23]:
resolved_df["issue_year"] = pd.to_datetime(
    resolved_df["issue_d"], format="%b-%y"
).dt.year
resolved_df["issue_year"].value_counts().sort_index()

issue_year
2007      251
2008     1562
2009     4716
2010    11522
2011    19683
2012    49591
2013    71414
2014    69307
Name: count, dtype: int64

In [24]:
resolved_df.groupby("issue_year").size()

issue_year
2007      251
2008     1562
2009     4716
2010    11522
2011    19683
2012    49591
2013    71414
2014    69307
dtype: int64

In [25]:
train_df = resolved_df[resolved_df["issue_year"] < 2014].copy()

test_df = resolved_df[resolved_df["issue_year"] == 2014].copy()

In [26]:
train_df.shape, test_df.shape

((158739, 77), (69307, 77))

In [27]:
X_train = train_df.drop(columns=["target"])
y_train = train_df["target"]

X_test = test_df.drop(columns=["target"])
y_test = test_df["target"]

In [28]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((158739, 76), (158739,), (69307, 76), (69307,))

In [30]:
features = [
    "loan_amnt", "funded_amnt", "funded_amnt_inv",
    "int_rate", "installment", "annual_inc", "dti",
    "delinq_2yrs", "inq_last_6mths", "open_acc",
    "pub_rec", "revol_bal", "revol_util", "total_acc",
    "acc_now_delinq", "tot_coll_amt", "tot_cur_bal",
    "term", "grade", "sub_grade", "emp_length",
    "home_ownership", "verification_status", "purpose",
    "initial_list_status", "application_type"
]

In [31]:
X_train = train_df[features]
X_test = test_df[features]
X_train.shape, X_test.shape

((158739, 26), (69307, 26))

In [32]:
features

['loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'int_rate',
 'installment',
 'annual_inc',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'term',
 'grade',
 'sub_grade',
 'emp_length',
 'home_ownership',
 'verification_status',
 'purpose',
 'initial_list_status',
 'application_type']

In [33]:
X_train.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'int_rate',
       'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'term', 'grade',
       'sub_grade', 'emp_length', 'home_ownership', 'verification_status',
       'purpose', 'initial_list_status', 'application_type'],
      dtype='object')

In [34]:
numeric_features = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_features = X_train.select_dtypes(include=["object"]).columns.tolist()

In [35]:
numeric_features

['loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'int_rate',
 'installment',
 'annual_inc',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal']

In [36]:
categorical_features

['term',
 'grade',
 'sub_grade',
 'emp_length',
 'home_ownership',
 'verification_status',
 'purpose',
 'initial_list_status',
 'application_type']

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [38]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [39]:
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [40]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [41]:
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.linear_model import LogisticRegression

In [42]:
ml_pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42))
])

In [43]:
logistic_model = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("model", LogisticRegression(max_iter=1000))
])

In [44]:
logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['loan_amnt', 'funded_amnt',
                                                   'funded_amnt_inv',
                                                   'int_rate', 'installment',
                                                   'annual_inc', 'dti',
                                                   'delinq_2yrs',
                                                   'inq_last_6mths', 'open_acc',
                                                   'pub_rec', 'revol_bal',
                                                   'revol_util', 'total_acc',
                                                   'acc_now_d...
                                                   'tot_cur_bal']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['term', 'grade', 'sub_grade',
                                                   'emp_length',
                                                   'home_ownership',
                                                   'verification_status',
                                                   'purpose',
                                                   'initial_list_status',
                                                   'application_type'])])),
                ('smote', SMOTE(random_state=42)),
                ('model', LogisticRegression(max_iter=1000))])

In [46]:
y_prob = logistic_model.predict_proba(X_test)[:, 1]

In [47]:
y_pred = logistic_model.predict(X_test)

In [48]:
from sklearn.metrics import roc_auc_score, average_precision_score

In [49]:
roc_auc = roc_auc_score(y_test, y_prob)
pr_auc = average_precision_score(y_test, y_prob)

print("ROC-AUC:", roc_auc)
print("PR-AUC:", pr_auc)

ROC-AUC: 0.6972736846877217
PR-AUC: 0.36901271926352974

In [50]:
from sklearn.metrics import classification_report, confusion_matrix

In [51]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.64      0.74     54713
           1       0.32      0.65      0.43     14594

    accuracy                           0.64     69307
   macro avg       0.60      0.64      0.58     69307
weighted avg       0.76      0.64      0.67     69307

In [52]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[35020 19693]
 [ 5162  9432]]

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
rf_model = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("model", RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ))
])

In [55]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['loan_amnt', 'funded_amnt',
                                                   'funded_amnt_inv',
                                                   'int_rate', 'installment',
                                                   'annual_inc', 'dti',
                                                   'delinq_2yrs',
                                                   'inq_last_6mths', 'open_acc',
                                                   'pub_rec', 'revol_bal',
                                                   'revol_util', 'total_acc',
                                                   'acc_now_d...
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['term', 'grade', 'sub_grade',
                                                   'emp_length',
                                                   'home_ownership',
                                                   'verification_status',
                                                   'purpose',
                                                   'initial_list_status',
                                                   'application_type'])])),
                ('smote', SMOTE(random_state=42)),
                ('model', RandomForestClassifier(n_jobs=-1, random_state=42))])

In [56]:
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
y_pred_rf = rf_model.predict(X_test)

In [57]:
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix
)

In [58]:
roc_auc_rf = roc_auc_score(y_test, y_prob_rf)
pr_auc_rf = average_precision_score(y_test, y_prob_rf)

print("Random Forest ROC-AUC:", roc_auc_rf)
print("Random Forest PR-AUC:", pr_auc_rf)

Random Forest ROC-AUC: 0.6831943908152204
Random Forest PR-AUC: 0.3406392019776774

In [59]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.94      0.87     54713
           1       0.42      0.15      0.23     14594

    accuracy                           0.78     69307
   macro avg       0.61      0.55      0.55     69307
weighted avg       0.73      0.78      0.73     69307

In [60]:
cm_rf = confusion_matrix(y_test, y_pred_rf)

print("\nConfusion Matrix:")
print(cm_rf)

Confusion Matrix:
[[51585  3128]
 [12343  2251]]

In [62]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]

for threshold in thresholds:
    y_pred_threshold = (y_prob_rf >= threshold).astype(int)

    precision = precision_score(y_test, y_pred_threshold)
    recall = recall_score(y_test, y_pred_threshold)
    f1 = f1_score(y_test, y_pred_threshold)

    print(
        f"Threshold: {threshold} | "
        f"Precision: {precision:.3f} | "
        f"Recall: {recall:.3f} | "
        f"F1: {f1:.3f}"
    )

Threshold: 0.3 | Precision: 0.302 | Recall: 0.700 | F1: 0.422
Threshold: 0.4 | Precision: 0.357 | Recall: 0.412 | F1: 0.382
Threshold: 0.5 | Precision: 0.415 | Recall: 0.174 | F1: 0.245
Threshold: 0.6 | Precision: 0.443 | Recall: 0.043 | F1: 0.078
Threshold: 0.7 | Precision: 0.518 | Recall: 0.008 | F1: 0.016

In [64]:
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]

for threshold in thresholds:
    y_pred_threshold = (y_prob >= threshold).astype(int)

    precision = precision_score(y_test, y_pred_threshold)
    recall = recall_score(y_test, y_pred_threshold)
    f1 = f1_score(y_test, y_pred_threshold)

    print(
        f"Threshold: {threshold} | "
        f"Precision: {precision:.3f} | "
        f"Recall: {recall:.3f} | "
        f"F1: {f1:.3f}"
    )

Threshold: 0.3 | Precision: 0.249 | Recall: 0.921 | F1: 0.392
Threshold: 0.4 | Precision: 0.282 | Recall: 0.815 | F1: 0.419
Threshold: 0.5 | Precision: 0.324 | Recall: 0.646 | F1: 0.431
Threshold: 0.6 | Precision: 0.375 | Recall: 0.449 | F1: 0.409
Threshold: 0.7 | Precision: 0.436 | Recall: 0.242 | F1: 0.311

In [66]:
import pandas as pd

feature_importance = pd.DataFrame({
    "feature": rf_model.named_steps["preprocessor"].get_feature_names_out(),
    "importance": rf_model.named_steps["model"].feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="importance",
    ascending=False
)

feature_importance.head(15)

                            feature  importance
3                     num__int_rate    0.061476
5                   num__annual_inc    0.053816
16                 num__tot_cur_bal    0.048044
6                          num__dti    0.043714
12                  num__revol_util    0.043424
8               num__inq_last_6mths    0.040415
11                   num__revol_bal    0.040171
13                   num__total_acc    0.039996
9                     num__open_acc    0.039467
62        cat__emp_length_10+ years    0.038512
4                  num__installment    0.036109
2              num__funded_amnt_inv    0.035055
0                    num__loan_amnt    0.034169
1                  num__funded_amnt    0.033551
82  cat__purpose_debt_consolidation    0.032271

In [68]:
comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "ROC-AUC": [roc_auc, roc_auc_rf],
    "PR-AUC": [pr_auc, pr_auc_rf],
    "Precision": [0.324, 0.415],
    "Recall": [0.646, 0.174],
    "F1": [0.431, 0.245]
})

comparison

                 Model   ROC-AUC    PR-AUC  Precision  Recall     F1
0  Logistic Regression  0.697274  0.369013      0.324   0.646  0.431
1        Random Forest  0.683194  0.340639      0.415   0.174  0.245

In [69]:
logistic_features = logistic_model.named_steps["preprocessor"].get_feature_names_out()

logistic_coefficients = pd.DataFrame({
    "feature": logistic_features,
    "coefficient": logistic_model.named_steps["model"].coef_[0]
})

logistic_coefficients["abs_coefficient"] = (
    logistic_coefficients["coefficient"].abs()
)

logistic_coefficients = logistic_coefficients.sort_values(
    by="abs_coefficient",
    ascending=False
)

logistic_coefficients.head(15)

                        feature  coefficient  abs_coefficient
91  cat__purpose_small_business     0.661390         0.661390
1              num__funded_amnt     0.644636         0.644636
3                 num__int_rate     0.602346         0.602346
25                 cat__grade_G    -0.581850         0.581850
2          num__funded_amnt_inv    -0.466271         0.466271
5               num__annual_inc    -0.436800         0.436800
93         cat__purpose_wedding    -0.411135         0.411135
17         cat__term_ 36 months    -0.371253         0.371253
59            cat__sub_grade_G4    -0.363442         0.363442
80             cat__purpose_car    -0.298223         0.298223
20                 cat__grade_B     0.292507         0.292507
62    cat__emp_length_10+ years     0.260298         0.260298
24                 cat__grade_F    -0.257143         0.257143
86  cat__purpose_major_purchase    -0.252581         0.252581
18         cat__term_ 60 months     0.245583         0.245583